### ISSUE TITLE
Detected by AV

### ISSUE THREAD

**Issue by n0k0m3** [InfinityGhost/TabletDriver#21] opened 2019-10-28 15:40 UTC
https://www.virustotal.com/gui/file/6c9cd912bf436c6dec0010116d48c4cee8914ae9f4f3e660b68cfd1bf10a50c5/detection

Is this binary is safe to use? Its heuristic behavior is categorized as spyware/keylogger

## Hardware/software information
Windows Version: W10 1909

Tablet Driver version: 0.3.0

Tablet model:

**Comment by InfinityGhost** [comment] 2019-11-03 03:55
Similar to #16, the binaries should be completely safe. Rebuild them if you feel its a need to do so.

**Comment by InfinityGhost** [comment] 2019-11-03 03:56
If you get different results after building and uploading, please post them. But for now, I'm closing this issue as its a duplicate of a previous issue.

**Closed as completed by InfinityGhost** 2019-11-03 03:56 UTC
Labels: duplicate
